Repository AMReX-Codes/pyamrex, pull requests merged in 2022-08, with the labels that each got.

#52 add GeometryData and test
  src/Base/Geometry.cpp
  tests/test_geometry.py
Labels: enhancement

#56 CMake: 3.20+
  CMakeLists.txt
  README.md
  pyproject.toml
  setup.py
Labels: enhancement

#58 Pip: `PYBIND11_INTERNAL`
  README.md
  setup.py
Labels: enhancement

#59 README: LDRD Acknowledgement Notice
  README.md
Labels: documentation

#57 Python: 3.7+
  .github/workflows/dependencies/dependencies_clang6.sh
  .github/workflows/linux.yml
  README.md
  setup.py
Labels: enhancement

#61 RealBox: Extra Constructor
  src/Base/RealBox.cpp
  tests/test_realbox.py
Labels: enhancement

#62 Add More `Box` Methods
  src/Base/Box.cpp
  src/Base/IntVect.cpp
  tests/test_box.py
  tests/test_intvect.py
Labels: bug, enhancement

#63 Add: `MultiFab::sum_unique`
  src/Base/MultiFab.cpp
Labels: enhancement

#64 Windows: Fix `pip_install`
  .github/workflows/macos.yml
  .github/workflows/ubuntu.yml
  .github/workflows/windows.yml
  CMakeLists.txt
Labels: bug, enhancement

#65 Install Pre-Commit
  .editorconfig
  .github/workflows/dependencies/dependencies_nvcc11.sh
  .github/workflows/dependencies/documentation.sh
  .pre-commit-config.yaml
  setup.py
  src/AmrCore/AmrMesh.cpp
  src/Base/Geometry.cpp
  src/Base/PODVector.cpp
  src/Base/Periodicity.cpp
  src/Base/RealBox.cpp
  src/Base/Vector.cpp
  src/Particle/ArrayOfStructs.cpp
  src/Particle/Particle.cpp
  src/Particle/ParticleContainer.cpp
  src/Particle/ParticleTile.cpp
  src/amrex/__init__.py
  src/pyAMReX.cpp
  tests/conftest.py
  tests/test_aos.py
  tests/test_array4.py
  tests/test_box.py
  tests/test_coordsys.py
  tests/test_dim3.py
  tests/test_geometry.py
  tests/test_intvect.py
  tests/test_multifab.py
  tests/test_particle.py
  tests/test_particleContainer.py
  tests/test_particleTile.py
  tests/test_periodicity.py
  tests/test_podvector.py
  tests/test_realbox.py
  tests/test_realvect.py
  tests/test_soa.py
Labels: enhancement
