Repository AMReX-Codes/pyamrex, pull requests merged in 2023-10, with the labels that each got.

#198 CUDA Tests: Profiler in `cupyx` Now
  tests/test_multifab.py
Labels: gpu

#196 Copy to Host: Array4.to_numpy(copy=True)
  src/Base/Array4.H
  src/Base/Array4.cpp
  src/Base/Array4_complex.cpp
  src/Base/Array4_complex_const.cpp
  src/Base/Array4_float.cpp
  src/Base/Array4_float_const.cpp
  src/Base/Array4_int.cpp
  src/Base/Array4_int_const.cpp
  src/Base/Array4_uint.cpp
  src/Base/Array4_uint_const.cpp
  src/Base/BaseFab.cpp
  src/Base/CMakeLists.txt
  src/Base/MultiFab.cpp
  src/Base/PODVector.cpp
  src/amrex/Array4.py
  src/amrex/space1d/__init__.pyi
  src/amrex/space1d/amrex_1d_pybind/__init__.pyi
  src/amrex/space2d/__init__.pyi
  src/amrex/space2d/amrex_2d_pybind/__init__.pyi
  src/amrex/space3d/__init__.pyi
  src/amrex/space3d/amrex_3d_pybind/__init__.pyi
  tests/test_array4.py
  tests/test_basefab.py
  tests/test_multifab.py
Labels: enhancement, gpu

#195 Doc: More Implementation Details
  docs/source/acknowledge_us.rst
  docs/source/developers/implementation.rst
  docs/source/index.rst
  docs/source/usage/zerocopy.rst
Labels: documentation

#199 Release: 23.10
  CMakeLists.txt
  cmake/dependencies/AMReX.cmake
  docs/source/conf.py
  setup.py
  src/Particle/Particle.cpp
  src/Particle/ParticleContainer_ImpactX.cpp
  src/Particle/ParticleContainer_WarpX.cpp
  src/Particle/ParticleTile.cpp
  src/Particle/StructOfArrays.cpp
  src/amrex/space1d/__init__.pyi
  src/amrex/space1d/amrex_1d_pybind/__init__.pyi
  src/amrex/space2d/__init__.pyi
  src/amrex/space2d/amrex_2d_pybind/__init__.pyi
  src/amrex/space3d/__init__.pyi
  src/amrex/space3d/amrex_3d_pybind/__init__.pyi
Labels: documentation

#200 Badges: Zenodo, Beta
  .zenodo.json
  README.md
  setup.py
Labels: documentation

#203 CMake: `pip_install_nodeps` Target
  CMakeLists.txt
Labels: install

#206 Free Disk Space in Github CIs
  .github/workflows/codeql.yml
  .github/workflows/dependencies/ubuntu_free_disk_space.sh
Labels: enhancement

#204 Add grow_low and high to Box
  src/Base/Box.cpp
  src/amrex/space1d/amrex_1d_pybind/__init__.pyi
  src/amrex/space2d/amrex_2d_pybind/__init__.pyi
  src/amrex/space3d/amrex_3d_pybind/__init__.pyi
Labels: enhancement

#210 Tests: Managed Memory
  tests/conftest.py
Labels: gpu

#209 Fix: Pinned Allocators First
  src/Particle/ArrayOfStructs.cpp
  src/Particle/ParticleContainer.H
  src/Particle/ParticleTile.cpp
  src/Particle/StructOfArrays.cpp
  src/amrex/space1d/amrex_1d_pybind/__init__.pyi
  src/amrex/space2d/amrex_2d_pybind/__init__.pyi
  src/amrex/space3d/amrex_3d_pybind/__init__.pyi
Labels: bug

#211 Clean Tests & Includes
  src/amrex/ArrayOfStructs.py
  src/amrex/StructOfArrays.py
  src/amrex/space1d/__init__.py
  src/amrex/space2d/__init__.py
  src/amrex/space3d/__init__.py
  tests/conftest.py
  tests/test_aos.py
  tests/test_array4.py
  tests/test_basefab.py
  tests/test_coordsys.py
  tests/test_dim3.py
  tests/test_farraybox.py
  tests/test_geometry.py
  tests/test_multifab.py
  tests/test_parmparse.py
  tests/test_particleContainer.py
  tests/test_particleTile.py
  tests/test_periodicity.py
  tests/test_podvector.py
  tests/test_realbox.py
  tests/test_soa.py
Labels: enhancement

#217 Install: CMake Config & Targets
  CMakeLists.txt
  cmake/dependencies/AMReX.cmake
  pyAMReXConfig.cmake.in
  src/amrex/space1d/__init__.pyi
  src/amrex/space1d/amrex_1d_pybind/__init__.pyi
  src/amrex/space2d/__init__.pyi
  src/amrex/space2d/amrex_2d_pybind/__init__.pyi
  src/amrex/space3d/__init__.pyi
  src/amrex/space3d/amrex_3d_pybind/__init__.pyi
Labels: enhancement, install

#180 Remove distutils
  README.md
  pyproject.toml
  setup.py
Labels: enhancement, install
