Repository AMReX-Codes/pyamrex, pull requests merged in 2024-03, with the labels that each got.

#272 Fix: Windows add_dll_directory Expand
  src/amrex/space1d/__init__.py
  src/amrex/space2d/__init__.py
  src/amrex/space3d/__init__.py
Labels: bug, bug: affects latest release

#274 Fix: set_rdata/idata Vectors
  src/Particle/Particle.cpp
Labels: bug, bug: affects latest release

#273 Doc: Simple Compute (Helpers)
  docs/source/usage/compute.rst
  tests/test_multifab.py
  tests/test_particleContainer.py
Labels: component: documentation, component: tests, component: third party

#275 Release: 24.03
  CMakeLists.txt
  cmake/dependencies/AMReX.cmake
  docs/source/conf.py
  setup.py
Labels: component: documentation

#276 Particles: Restructure
  .github/workflows/ubuntu.yml
  docs/source/usage/api.rst
  src/Particle/ArrayOfStructs.H
  src/Particle/CMakeLists.txt
  src/Particle/Particle.H
  src/Particle/ParticleContainer.H
  src/Particle/ParticleContainer.cpp
  src/Particle/ParticleTile.H
  src/Particle/StructOfArrays.H
  src/pyAMReX.cpp
  tests/test_particle.py
  tests/test_particleContainer.py
  tests/test_particleTile.py
  tests/test_soa.py
Labels: component: particles

#278 CI: `isort` + `black` compatibility
  .pre-commit-config.yaml
  pyproject.toml
  src/amrex/space1d/__init__.py
  src/amrex/space1d/__init__.pyi
  src/amrex/space2d/__init__.py
  src/amrex/space2d/__init__.pyi
  src/amrex/space3d/__init__.py
  src/amrex/space3d/__init__.pyi
Labels: component: tests

#282 Add `.copy` for MultiFab
  src/Base/MultiFab.cpp
  src/amrex/MultiFab.py
  tests/test_multifab.py
Labels: enhancement

#284 AMReX: Update to latest development
  cmake/dependencies/AMReX.cmake
Labels: component: third party
