Repository AMReX-Codes/pyamrex, pull requests merged in 2024-04, with the labels that each got.

#222 Particle Container: Runtime Arguments
  src/Base/PODVector.cpp
  src/Particle/ParticleContainer.H
  tests/test_particleContainer.py
Labels: enhancement

#287 Doc: MultiFab Args & Doc Strings
  src/Base/MultiFab.cpp
  src/amrex/Array4.py
  src/amrex/MultiFab.py
Labels: component: documentation

#285 Release: 24.04
  CMakeLists.txt
  cmake/dependencies/AMReX.cmake
  docs/source/conf.py
  setup.py
Labels: component: documentation

#291 pybind11: v2.12.0
  README.md
  cmake/dependencies/pybind11.cmake
  docs/source/install/dependencies.rst
Labels: component: third party

#292 Add `MFItInfo`
  src/Base/MultiFab.cpp
Labels: enhancement

#293 Add overload for `sum_unique`
  cmake/dependencies/AMReX.cmake
  src/Base/MultiFab.cpp
Labels: enhancement

#295 Box: lo/hi small/big End Setters
  docs/source/usage/api.rst
  src/Base/Box.cpp
  tests/test_box.py
Labels: enhancement

#302 Update HIP CI for ROCm 6.1.0
  .github/workflows/hip.yml
Labels: component: tests, backend: hip

#303 Doc: Latest Papers
  docs/source/acknowledge_us.rst
Labels: component: documentation

#300 `Geometry`: Doc Strings
  src/Base/Geometry.cpp
  tests/test_geometry.py
  tests/test_particleContainer.py
Labels: component: documentation, API: breaking

#304 `isort`: AMReX as First Party Module
  pyproject.toml
Labels: bug, component: tests

#271 Python bindings for AMReX-MPMD
  src/Base/CMakeLists.txt
  src/Base/MPMD.cpp
  src/pyAMReX.cpp
  tests/test_MPMD/test_1/GNUmakefile
  tests/test_MPMD/test_1/Make.package
  tests/test_MPMD/test_1/main.cpp
  tests/test_MPMD/test_1/main.py
Labels: enhancement
