Repository AMReX-Codes/pyamrex, pull requests merged in 2024-11, with the labels that each got.

#387 Fix case when only empty tuple is passed in
  src/amrex/extensions/MultiFab.py
Labels: bug: affects latest release

#389 Update CXXFLAGS in SYCL CIs
  .github/workflows/intel.yml
Labels: install

#388 Add wrapper for VisMF
  src/Base/CMakeLists.txt
  src/Base/VisMF.cpp
  src/pyAMReX.cpp
Labels: enhancement
