Repository AMReX-Codes/pyamrex, pull requests merged in 2024-05, with the labels that each got.

#306 MultiFab: Fix Constructor Defaults
  src/Base/MultiFab.cpp
Labels: bug

#307 Fix CMake: CUDA Compile Features
  CMakeLists.txt
Labels: backend: cuda, install

#309 SoA: Fix CuPy
  src/amrex/StructOfArrays.py
Labels: bug, bug: affects latest release, component: particles

#308 CI: Fix macOS
  .github/workflows/dependencies/dependencies_mac.sh
  .github/workflows/macos.yml
Labels: component: tests

#289 `to_xp`: AoS, SoA, PODVector, MF, Array4
  docs/source/usage/zerocopy.rst
  src/amrex/Array4.py
  src/amrex/ArrayOfStructs.py
  src/amrex/MultiFab.py
  src/amrex/PODVector.py
  src/amrex/StructOfArrays.py
  tests/conftest.py
  tests/test_aos.py
  tests/test_multifab.py
  tests/test_particleContainer.py
  tests/test_particleTile.py
  tests/test_soa.py
Labels: enhancement, backend: cuda, backend: openmp

#310 Release: 24.05
  CMakeLists.txt
  cmake/dependencies/AMReX.cmake
  docs/source/conf.py
  setup.py
Labels: component: documentation

#312 README.rst in tests/test_MPMD/test_1
  .zenodo.json
  tests/test_MPMD/test_1/README.rst
  tests/test_MPMD/test_1/main.cpp
  tests/test_MPMD/test_1/main.py
Labels: component: documentation

#313 Doc: Fix Case-Sensitive AMReX Compile Options
  docs/source/install/cmake.rst
Labels: bug, component: documentation, install, bug: affects latest release

#314 CI: Update ROCm/HIP
  .github/workflows/dependencies/hip.sh
Labels: component: tests, backend: hip, component: third party

#316 Build: MPMD w/ MPI Only
  src/Base/CMakeLists.txt
Labels: bug, install, bug: affects latest release, component: MPI

#315 Amend Notices for Non-Endorsement
  NOTICE
  README.md
Labels: component: documentation

#319 Move Python Runtime Extensions
  src/amrex/extensions/Array4.py
  src/amrex/extensions/ArrayOfStructs.py
  src/amrex/extensions/Iterator.py
  src/amrex/extensions/MultiFab.py
  src/amrex/extensions/PODVector.py
  src/amrex/extensions/ParticleComponentNames.py
  src/amrex/extensions/ParticleContainer.py
  src/amrex/extensions/StructOfArrays.py
  src/amrex/extensions/__init__.py
  src/amrex/space1d/__init__.py
  src/amrex/space2d/__init__.py
  src/amrex/space3d/__init__.py
Labels: enhancement

#321 CMake: No Deprecation Warnings
  CMakeLists.txt
Labels: install

#324 AMReX: Update to latest development
  cmake/dependencies/AMReX.cmake
  src/Base/Array4.H
  src/Base/Box.cpp
Labels: component: third party

#325 Doc: Link More Examples
  docs/source/usage/examples.rst
Labels: component: documentation
