Repository AMReX-Codes/pyamrex, pull requests merged in 2024-07, with the labels that each got.

#320 add PlotFileData bindings
  src/Base/PlotFileUtil.cpp
  tests/test_plotfiledata.py
  tools/plot_plotfile_2d.py
Labels: enhancement

#335 Release: 24.07
  CMakeLists.txt
  cmake/dependencies/AMReX.cmake
  docs/source/conf.py
  setup.py
Labels: component: documentation

#338 Docs: fix link to GitHub discussions page
  docs/source/index.rst
Labels: component: documentation

#339 Fix CMake IPO Control
  CMakeLists.txt
  cmake/pyAMReXFunctions.cmake
Labels: bug, install, bug: affects latest release

#340 Fix Ubuntu 20.04 CI
  .github/workflows/dependencies/dependencies_nvcc11.sh
  .github/workflows/hip.yml
  .github/workflows/intel.yml
  .github/workflows/ubuntu.yml
Labels: component: tests

#341 Fix SoA Test: No NaN Comparison
  tests/test_soa.py
Labels: bug, component: tests, bug: affects latest release

#344 Doc: NumPy 2 Works
  requirements.txt
Labels: component: documentation, install

#345 Add overload_cast to IntVect::dim3()
  src/Base/IntVect.cpp
Labels: enhancement
