Repository AMReX-Codes/pyamrex, pull requests merged in 2024-10, with the labels that each got.

#373 Release: 24.10
  CMakeLists.txt
  cmake/dependencies/AMReX.cmake
  docs/source/conf.py
  setup.py
Labels: component: documentation

#377 CMake: Fix List of Pip Options
  CMakeLists.txt
  README.md
  docs/source/install/cmake.rst
Labels: bug, install, bug: affects latest release

#379 AMReX: Update to latest `development`
  cmake/dependencies/AMReX.cmake
  src/Particle/ParticleContainer.H
  tests/test_soa.py
Labels: component: third party

#370 Implement multifab wrapper functionality from WarpX
  docs/source/usage/compute.rst
  src/amrex/extensions/MultiFab.py
  tests/test_multifab.py
Labels: enhancement

#381 `PYBIND11_FINDPYTHON=ON`
  CMakeLists.txt
  cmake/dependencies/pybind11.cmake
  setup.py
Labels: bug, install, bug: affects latest release

#380 Print IntVect values in repr
  src/Base/IntVect.cpp
Labels: enhancement
