Repository AMReX-Codes/pyamrex, pull requests merged in 2024-08, with the labels that each got.

#342 Add Particle I/O: restart & restart_checkpoint
  .github/workflows/intel.yml
  src/Particle/CMakeLists.txt
  src/Particle/ParticleContainer.H
  src/Particle/ParticleContainer.cpp
  src/Particle/ParticleContainer_FHDeX.cpp
  tests/test_plotfileparticledata.py
Labels: component: particles

#347 CI: Clarify GCC Debug Runner
  .github/workflows/ubuntu.yml
  .github/workflows/windows.yml
Labels: component: documentation, component: tests

#350 CI: Fix to ROCm 6.1
  .github/workflows/dependencies/hip.sh
  .github/workflows/hip.yml
Labels: component: tests, component: third party

#346 Release: 24.08
  CMakeLists.txt
  cmake/dependencies/AMReX.cmake
  docs/source/conf.py
  setup.py
Labels: component: documentation

#351 CI: Ruff replaced Tools
  .pre-commit-config.yaml
Labels: component: tests

#352 AMReX: Update to latest `development`
  cmake/dependencies/AMReX.cmake
  src/Base/Box.cpp
Labels: component: third party

#356 Ruff: Run on pyi files
  .pre-commit-config.yaml
  src/amrex/space1d/__init__.pyi
  src/amrex/space2d/__init__.pyi
  src/amrex/space3d/__init__.pyi
Labels: component: tests, component: third party

#353 CMake: More Pip Control Options
  CMakeLists.txt
  README.md
  docs/source/install/cmake.rst
Labels: install

#359 CMake: Replace `FetchContent_Populate`
  CMakeLists.txt
  README.md
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/pybind11.cmake
  docs/source/install/dependencies.rst
  pyproject.toml
  setup.py
Labels: install, warning

#360 CI: Save PR Number Once
  .github/workflows/codeql.yml
Labels: bug, component: tests

#362 Revert "Simplify cache cleanup actions"
  .github/workflows/ci.yml
  .github/workflows/cleanup-cache-postpr.yml
  .github/workflows/cleanup-cache.yml
  .github/workflows/post-pr.yml
Labels: bug
