Repository AMReX-Codes/pyamrex, pull requests merged in 2024-09, with the labels that each got.

#364 Release: 24.09
  CMakeLists.txt
  cmake/dependencies/AMReX.cmake
  docs/source/conf.py
  setup.py
Labels: component: documentation

#365 Simplify cache cleanup actions
  .github/workflows/ci.yml
  .github/workflows/cleanup-cache-postpr.yml
  .github/workflows/cleanup-cache.yml
  .github/workflows/post-pr.yml
Labels: component: tests

#366 EB: On by Default in Superbuild
  cmake/dependencies/AMReX.cmake
  src/Base/AMReX.cpp
Labels: install

#369 Anticipate new `AddReal/IntComp` Overloads
  src/Particle/ParticleContainer.H
Labels: enhancement
