Repository AMReX-Codes/pyamrex, pull requests merged in 2025-09, with the labels that each got.

#477 Fix MultiFab getitem for single imaginary index
  src/amrex/extensions/MultiFab.py
Labels: bug: affects latest release

#474 Implement same dependency/release update workflow as WarpX
  CMakeLists.txt
  MANIFEST.in
  cmake/dependencies/AMReX.cmake
  cmake/dependencies/pybind11.cmake
  dependencies.json
  docs/source/conf.py
  setup.py
  update_dependencies.py
Labels: automation

#478 Fix Use-After-Free in NumPy/df
  src/amrex/extensions/ArrayOfStructs.py
  src/amrex/extensions/PODVector.py
Labels: bug, bug: affects latest release

#479 Fix Warning: GNU 11 + NVCC 11.7
  cmake/pyAMReXFunctions.cmake
Labels: backend: cuda, warning
