Repository AMReX-Codes/pyamrex, pull requests merged in 2025-05, with the labels that each got.

#436 Bump Ubuntu from 20.04 -> 24.04 in CI
  .github/workflows/dependencies/dependencies_clang18.sh
  .github/workflows/dependencies/dependencies_gcc14.sh
  .github/workflows/dependencies/dependencies_nvcc12.sh
  .github/workflows/dependencies/hip.sh
  .github/workflows/hip.yml
  .github/workflows/ubuntu.yml
Labels: component: tests

#430 Tests: `amrex.the_arena_init_size=0`
  tests/conftest.py
Labels: backend: cuda, component: tests, backend: sycl, backend: hip

#437 pyproject: CMake 4 is fine
  pyproject.toml
Labels: install
