Repository AMReX-Codes/pyamrex, pull requests merged in 2025-03, with the labels that each got.

#417 ParmParse: `pretty_print_table`
  src/Base/ParmParse.cpp
  src/pyAMReX.H
  tests/test_parmparse.py
Labels: enhancement

#418 Particles: w/o HiPACE++
  src/Particle/CMakeLists.txt
  src/Particle/ParticleContainer.cpp
  src/Particle/ParticleContainer_HiPACE.cpp
Labels: component: particles

#416 Release 25.03
  CMakeLists.txt
  cmake/dependencies/AMReX.cmake
  docs/source/conf.py
  setup.py
Labels: component: documentation

#421 `SmallMatrix.__repr__` like NumPy
  src/Base/SmallMatrix.H
Labels: enhancement

#422 pytest: less verbose
  tests/conftest.py
Labels: component: tests
