Repository AMReX-Codes/pyamrex, pull requests merged in 2025-08, with the labels that each got.

#458 Single Precision Support
  .github/workflows/ubuntu.yml
  setup.py
  src/Base/AMReX.cpp
  src/Particle/ArrayOfStructs.H
  tests/test_aos.py
  tests/test_parmparse.py
  tests/test_particle.py
  tests/test_particleContainer.py
  tests/test_particleTile.py
  tests/test_realbox.py
  tests/test_realvect.py
Labels: bug, bug: affects latest release

#462 Release: 25.08
  CMakeLists.txt
  cmake/dependencies/AMReX.cmake
  docs/source/conf.py
  setup.py
Labels: component: documentation

#465 Config: SIMD Details
  src/Base/AMReX.cpp
Labels: component: documentation, component: third party

#467 Modernize compile warnings using CMake's target_compile_options
  CMakeLists.txt
  cmake/pyAMReXFunctions.cmake
Labels: install
